site_name: notes
site_url: https://a7Bz3tQ9.github.io/

nav:
  - 首页: index.md
  - 比赛分析:
    - CSP-S 2025 分析: 比赛分析/CSP-S 2025.md
  - 专题训练:
    - 图论:
      - 最短路+最小生成树: 专题训练/图论/图论.md
      - 最短路: 专题训练/图论/最短路.md
      - 最小生成树: 专题训练/图论/最小生成树.md
      - 拓扑排序: 专题训练/图论/拓扑排序.md
      - 欧拉回路: 专题训练/图论/欧拉回路.md
    - DP:
      - 状压 DP: 专题训练/DP/状压 DP.md
      - 树形 DP: 专题训练/DP/树形 DP.md
      - 树形 DP 2: 专题训练/DP/树形 DP 2.md
      - 数位 DP: 专题训练/DP/数位 DP.md
      - DP 优化: 专题训练/DP/DP 优化.md
      - 斜率优化: 专题训练/DP/斜率优化.md
      - wqs 二分: 专题训练/DP/wqs 二分.md 
    - 数据结构:
      - 单调栈: 专题训练/数据结构/单调栈.md
      - 并查集: 专题训练/数据结构/并查集.md
      - 线段树基础: 专题训练/数据结构/线段树基础.md
      - 树状数组: 专题训练/数据结构/树状数组.md
    - 数学:
      - 组合数学: 专题训练/数学/组合数学.md
      - 卡特兰数: 专题训练/数学/卡特兰数.md
      - 组合计数: 专题训练/数学/组合计数.md
      - 数论基础: 专题训练/数学/数论.md
    - 字符串:
      - 字符串 1: 专题训练/字符串/字符串 1.md
      - 字符串 2: 专题训练/字符串/字符串 2.md
    - 其他:
      - 贪心: 专题训练/其他/贪心.md
      - 贪心 2: 专题训练/其他/贪心 2.md
      - 二分: 专题训练/其他/二分.md
      - 整体二分: 专题训练/其他/整体二分.md
      - 分治: 专题训练/其他/分治.md
theme:
  name: material
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search
    - content.action.edit
    - navigation.tabs
    - navigation.instant
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - content.code.copy #代码复制
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share
    - navigation.tracking

  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css  # KaTeX样式
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js   # KaTeX核心
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js  # 自动渲染
  - javascripts/katex.js

plugins:
  - search

markdown_extensions: #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - markdown.extensions.toc:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  #     permalink: "\ue157"

